@echo off
rem ============================================================
rem  构建 nattunnel-client.exe (PyInstaller, 单文件, 控制台窗口)
rem  在 client/ 目录运行:
rem      build.bat                             默认写死 http://127.0.0.1:8000 (本地调试)
rem      build.bat -s https://www.xxx.com     把公网服务器地址写死进 exe
rem  产物: dist\nattunnel-client.exe (运行时无需 config.json, 只需 -a <绑定令牌>)
rem  图标:   仓库根 favicon.ico (--icon 打进 exe; 缺失时用默认图标)
rem  注意:  URL 中不要包含 % 字符(batch 转义问题)
rem ============================================================
cd /d %~dp0

set "SERVER_URL="
:parse_args
if "%~1"=="" goto parsed
if /i "%~1"=="-s" ( set "SERVER_URL=%~2" & shift & shift & goto parse_args )
if /i "%~1"=="--server" ( set "SERVER_URL=%~2" & shift & shift & goto parse_args )
shift
goto parse_args
:parsed
if "%SERVER_URL%"=="" set "SERVER_URL=http://127.0.0.1:8000"
echo [build] 服务器地址写死进 exe: %SERVER_URL%

rem 生成 build_config.py(构建时写死的服务器地址, 随 PyInstaller 打进 exe)
>build_config.py echo # Auto-generated by build.bat - do not edit (baked into the exe)
>>build_config.py echo SERVER = "%SERVER_URL%"

where python >nul 2>&1 || (echo 未找到 python & exit /b 1)

if not exist .venv python -m venv .venv
.venv\Scripts\python.exe -m pip install --upgrade pip
.venv\Scripts\python.exe -m pip install -r requirements.txt pyinstaller

rem exe 图标: 仓库根的 favicon.ico(不存在则跳过, 不中断构建)
set ICONFLAG=
if exist ..\favicon.ico set ICONFLAG=--icon ..\favicon.ico

rem pyinstaller-hooks-contrib 已自动处理依赖
.venv\Scripts\pyinstaller.exe --noconfirm --onefile --console ^
  --name nattunnel-client ^
  %ICONFLAG% ^
  nattunnel_client.py
