@echo off
rem ============================================================
rem  Build nattunnel-client.exe (PyInstaller, single file)
rem
rem  Usage (from the client\ directory):
rem      build.bat                             bake http://127.0.0.1:8000 (local debug default)
rem      build.bat -s https://www.xxx.com     bake your public server address into the exe
rem
rem  The server URL may omit the scheme and/or carry a trailing path
rem  (e.g. "www.keliit.top/tunnel/"); the client normalizes it at start.
rem
rem  Output : dist\nattunnel-client.exe - runs with just -a <bound-token>, no config file
rem           (also copied to ..\server\app\static\nattunnel-client.exe as a static download asset)
rem  Icon   : ..\favicon.ico is embedded when present (default icon otherwise)
rem  Note   : do not use % characters in the URL (batch escaping)
rem
rem  IMPORTANT: keep this script pure ASCII - cmd.exe on Chinese Windows
rem  parses .bat with the OEM codepage and mangles UTF-8 CJK text.
rem ============================================================
cd /d %~dp0

set "SERVER_URL="
:parse_args
if "%~1"=="" goto parsed
if /i "%~1"=="-s" ( set "SERVER_URL=%~2" & shift & shift & goto parse_args )
if /i "%~1"=="--server" ( set "SERVER_URL=%~2" & shift & shift & goto parse_args )
shift
goto parse_args
:parsed
if "%SERVER_URL%"=="" set "SERVER_URL=http://127.0.0.1:8000"
echo [build] baking server address into exe: %SERVER_URL%

rem generate build_config.py (server address baked at build time)
>build_config.py echo # Auto-generated by build.bat - do not edit (baked into the exe)
>>build_config.py echo SERVER = "%SERVER_URL%"

where python >nul 2>&1 || (echo python not found & exit /b 1)

if not exist .venv python -m venv .venv
.venv\Scripts\python.exe -m pip install --upgrade pip
.venv\Scripts\python.exe -m pip install -r requirements.txt pyinstaller

rem exe icon: favicon.ico at repo root (skip if missing, never abort build)
set ICONFLAG=
if exist ..\favicon.ico set ICONFLAG=--icon ..\favicon.ico

rem pyinstaller-hooks-contrib handles dependencies automatically
.venv\Scripts\pyinstaller.exe --noconfirm --onefile --console ^
  --name nattunnel-client ^
  %ICONFLAG% ^
  nattunnel_client.py

rem copy the built exe into server/app/static so the web admin can also
rem offer a plain static download link (nattunnel-client.exe, no login needed)
if exist "dist\nattunnel-client.exe" (
    echo [copy] dist\nattunnel-client.exe -^> ..\server\app\static\nattunnel-client.exe
    copy /y "dist\nattunnel-client.exe" "..\server\app\static\nattunnel-client.exe" >nul
    if errorlevel 1 echo WARNING: static copy failed (check server\app\static exists)
) else (
    echo WARNING: dist\nattunnel-client.exe not found - build may have failed, static copy skipped
)
